apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  replicas: 1
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           imagePullPolicy: Always
           ports:
             - containerPort: PORT_CONTAINER
           resources:
             requests:
               memory: "256Mi"
               cpu: "100m"
             limits:
               memory: "512Mi"
               cpu: "200m"
           livenessProbe:
             httpGet:
               path: /health
               port: PORT_CONTAINER
             initialDelaySeconds: 30
             periodSeconds: 10
           readinessProbe:
             httpGet:
               path: /health
               port: PORT_CONTAINER
             initialDelaySeconds: 5
             periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: DEPLOYMENT_NAME-service
  namespace: NAMESPACE
spec:
  selector:
    project: PROJECT
  ports:
    - protocol: TCP
      port: PORT_CONTAINER
      targetPort: PORT_CONTAINER
  type: ClusterIP

